<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="HOME" failures="3" tests="6" name="Test1" time="124.708" errors="0" timestamp="2020-12-16T01:22:17 IST">
  <testcase classname="com.nopCommerceV2.testCases.TC_LoginTest_001" name="loginTest" time="23.317"/>
  <testcase classname="com.nopCommerceV2.testCases.TC_LoginDDT_002" name="LoginTest" time="22.897"/>
  <testcase classname="com.nopCommerceV2.testCases.TC_LoginDDT_002" name="LoginTest" time="8.73">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.nopCommerceV2.testCases.TC_LoginDDT_002.LoginTest(TC_LoginDDT_002.java:42)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1510)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- LoginTest -->
  <testcase classname="com.nopCommerceV2.testCases.TC_LoginDDT_002" name="LoginTest" time="8.565">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.nopCommerceV2.testCases.TC_LoginDDT_002.LoginTest(TC_LoginDDT_002.java:42)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1510)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- LoginTest -->
  <testcase classname="com.nopCommerceV2.testCases.TC_LoginDDT_002" name="LoginTest" time="8.489">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.nopCommerceV2.testCases.TC_LoginDDT_002.LoginTest(TC_LoginDDT_002.java:42)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1510)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- LoginTest -->
  <testcase classname="com.nopCommerceV2.testCases.TC_AddCustomerTest_003" name="addNewCustomer" time="32.916"/>
</testsuite> <!-- Test1 -->
